# Generated by Django 3.1.7 on 2021-03-19 14:52

import alpha.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters and digits only. No blank spaces', max_length=20, unique=True, validators=[alpha.validators.digits_and_letters_validator], verbose_name='username'),
        ),
    ]
